/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you want apcupsd support */
/* #undef APCUPSD */

/* Define for Audacious support */
/* #undef AUDACIOUS */

/* Define for Audacious Legacy support */
/* #undef AUDACIOUS_LEGACY */

/* Define if you want BMPx support */
/* #undef BMPX */

/* Configfile of the user */
#define CONFIG_FILE "$HOME/.conkyrc"

/* Define if you want conky to output a default config (with -C) */
/* #undef CONFIG_OUTPUT */

/* Define for debugging */
/* #undef DEBUG */

/* Default networkdevice */
#define DEFAULTNETDEV "eth0"

/* Default size used for temporary, static text buffers */
#define DEFAULT_TEXT_BUFFER_SIZE 256

/* Define if you want Eve-Online Skill monitor support */
/* #undef EVE */

/* Eve skilltree URL */
/* #undef EVEURL_SKILLTREE */

/* Eve training URL */
/* #undef EVEURL_TRAINING */

/* Eve output format */
/* #undef EVE_OUTPUT_FORMAT */

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
/* #undef HAVE_ALSA_ASOUNDLIB_H */

/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef HAVE_ARPA_INET_H */

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <audacious/audctrl.h> header file. */
/* #undef HAVE_AUDACIOUS_AUDCTRL_H */

/* Define to 1 if you have the <audacious/beepctrl.h> header file. */
/* #undef HAVE_AUDACIOUS_BEEPCTRL_H */

/* Define to 1 if you have the <audacious/dbus.h> header file. */
/* #undef HAVE_AUDACIOUS_DBUS_H */

/* Define to 1 if you have the `calloc' function. */
#define HAVE_CALLOC 1

/* Define if you have clock_gettime() */
#define HAVE_CLOCK_GETTIME 1

/* Define if you want Curl support */
#define HAVE_CURL 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the `fopencookie' function. */
/* #undef HAVE_FOPENCOOKIE */

/* Define to 1 if you have the `free' function. */
#define HAVE_FREE 1

/* Define to 1 if you have the `funopen' function. */
/* #undef HAVE_FUNOPEN */

/* Define to 1 if you have the `gethostbyname_r' function. */
/* #undef HAVE_GETHOSTBYNAME_R */

/* Define to 1 if you have the `getloadavg' function. */
#define HAVE_GETLOADAVG 1

/* Define to 1 if you have the `getnameinfo' function. */
/* #undef HAVE_GETNAMEINFO */

/* Define to 1 if you have the `gettimeofday' function. */
/* #undef HAVE_GETTIMEOFDAY */

/* Define to 1 if you have the <glib.h> header file. */
/* #undef HAVE_GLIB_H */

/* Define to 1 if you have the <glib-object.h> header file. */
/* #undef HAVE_GLIB_OBJECT_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you want wireless support */
/* #undef HAVE_IWLIB */

/* Define to 1 if you have the <iwlib.h> header file. */
/* #undef HAVE_IWLIB_H */

/* Define if you have kstat (Solaris) */
/* #undef HAVE_KSTAT */

/* Define to 1 if you have the `X11' library (-lX11). */
/* #undef HAVE_LIBX11 */

/* Define to 1 if you have the <linux/soundcard.h> header file. */
/* #undef HAVE_LINUX_SOUNDCARD_H */

/* Define if you want Lua scripting support */
#define HAVE_LUA 1

/* Define if you want Lua Cairo bindings for Conky */
#define HAVE_LUA_CAIRO 1

/* Define if you want Lua Imlib2 bindings for Conky */
#define HAVE_LUA_IMLIB2 1

/* Define to 1 if you have the `malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <mcheck.h> header file. */
/* #undef HAVE_MCHECK_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memrchr' function. */
#define HAVE_MEMRCHR 1

/* Define to 1 if you have the <ncurses.h> header file. */
#define HAVE_NCURSES_H 1

/* Define to 1 if you have the <netdb.h> header file. */
/* #undef HAVE_NETDB_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef HAVE_NETINET_IN_H */

/* Define to 1 if you have the <netinet/tcp.h> header file. */
/* #undef HAVE_NETINET_TCP_H */

/* Define to 1 if you have the <NVCtrl/NVCtrl.h> header file. */
/* #undef HAVE_NVCTRL_NVCTRL_H */

/* Define to 1 if you have the `popen' function. */
#define HAVE_POPEN 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the <semaphore.h> header file. */
#define HAVE_SEMAPHORE_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strndup' function. */
#define HAVE_STRNDUP 1

/* Define if struct statfs has the f_fstypename member */
/* #undef HAVE_STRUCT_STATFS_F_FSTYPENAME */

/* Define to 1 if you have the `sysinfo' function. */
/* #undef HAVE_SYSINFO */

/* Define to 1 if you have the <sys/inotify.h> header file. */
/* #undef HAVE_SYS_INOTIFY_H */

/* Define to 1 if you have the <sys/mount.h> header file. */
#define HAVE_SYS_MOUNT_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #undef HAVE_SYS_SOCKET_H */

/* Define to 1 if you have the <sys/statfs.h> header file. */
/* #undef HAVE_SYS_STATFS_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define for X11 Xdamage extension */
#define HAVE_XDAMAGE 1

/* Define for X11 double-buffering */
#define HAVE_XDBE 1

/* Define if you want hddtemp support */
/* #undef HDDTEMP */

/* Define if you want support for IBM/Lenovo notebooks (SMAPI) */
/* #undef IBM */

/* Define if you want Imlib2 support */
#define IMLIB2 1

/* Define if you want support for per-task I/O statistics */
/* #undef IOSTATS */

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define LT_OBJDIR ".libs/"

/* Define if you want Lua extras */
#define LUA_EXTRAS 1

/* Define if you want math support */
#define MATH 1

/* Maximum number of network devices */
#define MAX_NET_INTERFACES 64

/* Default maximum number of special things, e.g. fonts, offsets, aligns, etc.
   */
#define MAX_SPECIALS_DEFAULT 512

/* Default maximum size of config TEXT buffer, i.e. below TEXT line. */
#define MAX_USER_TEXT_DEFAULT 16384

/* Define if you want MOC support */
/* #undef MOC */

/* Define if you want MPD support */
#define MPD 1

/* Textencoding to use */
/* #undef MY_ENCODING */

/* Define for ncurses support */
#define NCURSES 1

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Define if you want nvidia support */
/* #undef NVIDIA */

/* Define if you want support for window creating */
#define OWN_WINDOW 1

/* Name of package */
#define PACKAGE "conky"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "brenden1@users.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Conky"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Conky 1.9.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "conky"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.9.0"

/* Define for profiling (gprof and gcov) support */
/* #undef PROFILING */

/* Define if you want Curl support */
#define RSS 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if you want tcp port monitoring support */
/* #undef TCP_PORT_MONITOR */

/* Define for testing (enables strict compiler flags) */
/* #undef TESTING */

/* Define if you want argb visual support */
#define USE_ARGB 1

/* Version number of package */
#define VERSION "1.9.0"

/* Define if you want METAR weather support */
/* #undef WEATHER */

/* Define if you want to use X11 */
#define X11 1

/* Define for Xft support */
#define XFT 1

/* Define if you want XMMS2 support */
/* #undef XMMS2 */

/* Define if you want XOAP weather support */
/* #undef XOAP */

/* User xoap keys file */
/* #undef XOAP_FILE */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define for GNU source and extensions */
#define _GNU_SOURCE 
